import { JEV_TOOL } from './jev-tool';
// Shared by the MCP server and read-only dashboard footprint measurement.
// Core entries are declared on every agent turn. Optional Jev is permission-gated at
// process creation; it is not switched by conversational turn type. For the core list: the advertised tool list is position 0 of
// Anthropic's cached [tools, system, messages] prefix, so a tool that appears on only some
// turns invalidates the entire cache each time it changes. Per-turn mode belongs in the
// prompt text below the cache breakpoint, never in this list. See response-schema.ts.
const schema = (properties: Record<string, unknown>, required: string[]) => ({ type: 'object', properties, required, additionalProperties: false });
const text = { type: 'string' };
export const AGENT_TASK_TOOLS: Array<{name:string;description:string;inputSchema:Record<string,unknown>}> = [
  JEV_TOOL,
  { name: 'capabilities_list', description: 'Discover all capabilities this agent can offer: installed/shared/native skills, gateway MCP tools and enabled connector/plugin MCP tools, including tools executed only by workers. Use scope=browser to discover explicitly installed browser targets in this conversation; there may be none. Browser work uses target_profile=gateway-managed and gateway_target adapter=browser. Use scope=safemode to discover authorized safemode sessions by name (for example astra2), native ID, CLI and owner status, without creating a task. Send authorized work through task_spawn target_profile=gateway-managed, not through a polling worker. Read metadata only; never executes a tool or grants permissions. Use query to find relevant tools before assigning work. Follow next_offset until null when the user asks for the complete list, passing catalog_version from the first page. On CAPABILITY_CATALOG_CHANGED restart from offset 0. Report unavailable discovery honestly; do not confuse your own restricted callable tools with the capabilities of the agent as a whole.', inputSchema: schema({scope:{type:'string',enum:['capabilities','safemode','browser']},query:text,catalog_version:text,offset:{type:'integer',minimum:0}},[]) },
  { name: 'conversation_intake', description: 'Only when this turn\'s instructions explicitly ask you to run intake: prepare executable work, incomplete materials, or an amendment to an existing task. Without that instruction this turn, do not call it at all — answer the user directly and use the task tools directly. Do not call it for greetings, introductions, casual conversation or questions you can answer directly; answer those normally once. When semantic intake is enabled, acknowledge before work mutations. Incomplete material is inspected now; the gateway asks the supplied clarification after the configured silence interval, not on every item.',
    inputSchema: schema({mode:{type:'string',enum:['ready','wait','update','resolve']},resolution:{type:'string',description:'For resolve: explain how deferred work was cancelled, replaced or fulfilled. When linking newly committed work, include task_id from this decision.'},acknowledgement:{type:'string',description:'A brief contextual message addressed directly to the user about the work you will do. Immediately displayed and spoken aloud. Never include private classification, reasoning, or instructions to yourself.'},preparation:text,clarification:text,task_id:text},['mode']) },
  { name: 'task_spawn', description: 'Durably queue a Worker task, or a Gateway-managed task targeting an existing external session. For safemode, discover the session with capabilities_list scope=safemode, then use target_profile=gateway-managed and gateway_target. The gateway tracks completion and reports automatically without a polling worker. takeover requires explicit user permission to stop the current interactive owner. no_bootstrap omits the introduction but preserves diagnostics and sandbox restrictions. Returns after commit, before execution. Gateway-managed tasks accept text instructions; attachments must be described explicitly and are not forwarded.',
    inputSchema: schema({ retry_of: {type:'string',description:'When correcting a rejected task_spawn, copy retry_of from its error response. Identifies the failed command this retry replaces, including when correcting its instructions. Omit for new or unrelated work.'}, title: text, instructions: text, target_profile: text, gateway_target: schema({adapter:{type:'string',enum:['safemode','browser']},session_id:text,takeover:{type:'boolean'},no_bootstrap:{type:'boolean'}},['adapter','session_id']), working_directory: { type:'string', description:'Host workers only: absolute user-authorized project directory in which to start the worker. Supply the canonical checkout when the user specifies one. Does not create a worktree. Follow-up tasks inherit the prior host directory when omitted; otherwise the configured project root or agent workspace is used. Unavailable for app containers and isolated workspace modes.' }, spoken_acknowledgement: { type: 'string', description: 'Required for live voice: a short natural response in the user language explaining the specific work you are about to do. Describe the specific user request as your own task, in the voice of your existing persona; do not announce handing it to a worker or use a generic acknowledgement. Speak as the person doing the work; avoid Thai delegation phrases such as สั่งเช็คแล้ว, สั่งไปแล้ว or ส่งให้ตรวจแล้ว. Describe queued work as accepted/to do next, and only say it is running when that state is confirmed. Do not claim completion. The gateway manages playback and channel text-before-voice ordering.' }, skill_name: { type: 'string', description: 'Exact installed gateway or discovered Claude Code runtime skill name for skill-worker. Native skills are invoked directly by the CLI; shared/workspace skills are supplied with their resources. Never supply a file path.' }, skill_args: { type: 'string', description: 'Arguments for the installed skill; required with skill_name.' }, continue_task_id: { type: 'string', description: 'Prior task ID in this conversation for related follow-up work. Reuses its worker session when compatible; waits for success by default. Queue every authorized dependent step now, using each returned task ID for the next step. Omit for independent work.' }, continuation_policy: { type: 'string', enum: ['after_success', 'after_terminal'], description: 'With continue_task_id: after_success (default) starts only after the predecessor succeeds; otherwise fails without executing. Use after_terminal only for explicitly authorized recovery/inspection that must run after failure or cancellation.' }, context_refs: { type: 'array', items: text, description: 'Only orchestration input IDs, authorized attachment refs or task artifact IDs. Put project filenames in instructions instead.' } }, ['title', 'instructions', 'target_profile']) },
  { name: 'task_status', description: 'Read the task index in this conversation without waiting. Pass task_id to retrieve the complete stored result and evidence before discussing an earlier task. An index entry is not a partial worker report.', inputSchema: schema({ task_id: text }, []) },
  { name: 'task_cancel', description: 'Request cancellation, including needs_reconciliation cleanup. cancel_requested is not proof of termination. Existing files are retained. Set replaced_by_task_id only for a known replacement task, never infer from similar titles.', inputSchema: schema({ task_id: text, replaced_by_task_id: text }, ['task_id']) },
  { name: 'task_update', description: 'Accept a revised task instruction. applied_revision changes only when the worker accepts it. Gateway-managed tasks can only be amended before dispatch; for an already sent request queue a follow-up task with continue_task_id.', inputSchema: schema({ retry_of: {type:'string',description:'When correcting a rejected task_update for this same task, copy retry_of from its error response. Omit for unrelated changes.'}, task_id: text, expected_revision: { type: 'integer', minimum: 1 }, instruction: text, mode: { type: 'string', enum: ['when_ready', 'interrupt_and_resume'] } }, ['task_id', 'expected_revision', 'instruction', 'mode']) },
  { name: 'task_question', description: 'Manage pending questions without answering or resuming work. Ask stages one natural separate message after your reply; discuss marks ongoing consultation; defer/mute/resume persist the user reminder preference.', inputSchema: schema({ action: { type: 'string', enum: ['ask','discuss','defer','mute','resume'] }, question_ids: { type: 'array', items: text, minItems: 1, maxItems: 20 }, text, delay_ms: { type: 'integer', minimum: 60000, maximum: 2592000000 } }, ['action', 'question_ids']) },
  { name: 'task_answer', description: 'Answer the matching pending question on a task.', inputSchema: schema({ task_id: text, question_id: text, answer: text }, ['task_id', 'question_id', 'answer']) },
];
