// AUTO-GENERATED by scripts/gen-cli.ts — DO NOT EDIT.
// Regenerate with: npm run gen-cli
import { GeneratedCommand } from './types';

export const GENERATED_COMMANDS: GeneratedCommand[] = [
  {
    "noun": "crons",
    "verb": "create",
    "method": "POST",
    "path": "/v1/crons",
    "args": [],
    "flags": [
      {
        "name": "agentId",
        "in": "body",
        "required": true,
        "description": "Owning agent id"
      },
      {
        "name": "name",
        "in": "body",
        "required": true,
        "description": "Job name"
      },
      {
        "name": "type",
        "in": "body",
        "description": "command | agent"
      },
      {
        "name": "schedule",
        "in": "body",
        "description": "5-field cron expression (scheduleKind=cron)"
      },
      {
        "name": "scheduleKind",
        "in": "body",
        "description": "cron | at"
      },
      {
        "name": "scheduleAt",
        "in": "body",
        "description": "ISO-8601 timestamp (scheduleKind=at)"
      },
      {
        "name": "command",
        "in": "body",
        "description": "Shell command (type=command)"
      },
      {
        "name": "prompt",
        "in": "body",
        "description": "Agent prompt (type=agent)"
      }
    ],
    "summary": "Create a cron job",
    "auth": "key"
  },
  {
    "noun": "crons",
    "verb": "delete",
    "method": "DELETE",
    "path": "/v1/crons/:id",
    "args": [
      "id"
    ],
    "flags": [],
    "summary": "Delete a cron job",
    "auth": "key"
  },
  {
    "noun": "crons",
    "verb": "get",
    "method": "GET",
    "path": "/v1/crons/:id",
    "args": [
      "id"
    ],
    "flags": [],
    "summary": "Get a single cron job",
    "auth": "key"
  },
  {
    "noun": "crons",
    "verb": "list",
    "method": "GET",
    "path": "/v1/crons",
    "args": [],
    "flags": [
      {
        "name": "agent",
        "in": "query",
        "description": "Filter by agent id"
      }
    ],
    "summary": "List cron jobs accessible by this key",
    "auth": "key"
  },
  {
    "noun": "crons",
    "verb": "run",
    "method": "POST",
    "path": "/v1/crons/:id/run",
    "args": [
      "id"
    ],
    "flags": [],
    "summary": "Trigger a cron job now",
    "auth": "key"
  },
  {
    "noun": "crons",
    "verb": "runs",
    "method": "GET",
    "path": "/v1/crons/:id/runs",
    "args": [
      "id"
    ],
    "flags": [
      {
        "name": "limit",
        "in": "query",
        "description": "Max runs to return (default 20)"
      }
    ],
    "summary": "Get cron job run history",
    "auth": "key"
  },
  {
    "noun": "crons",
    "verb": "status",
    "method": "GET",
    "path": "/v1/crons/status",
    "args": [],
    "flags": [],
    "summary": "Cron scheduler status",
    "auth": "key"
  },
  {
    "noun": "crons",
    "verb": "update",
    "method": "PUT",
    "path": "/v1/crons/:id",
    "args": [
      "id"
    ],
    "flags": [],
    "summary": "Update a cron job",
    "auth": "key"
  }
];

export const GENERATED_NOUNS: string[] = ["crons"];
