/**
 * Code generator: turns the route manifest (single source of truth) into
 *   - src/cli/commands.generated.ts  (the CLI's friendly command table), and
 *   - CLI.md                         (the CLI reference doc).
 *
 * Run:   ./node_modules/.bin/ts-node scripts/gen-cli.ts
 * Check: ./node_modules/.bin/ts-node scripts/gen-cli.ts --check   (CI drift guard)
 *
 * Because the command table and docs are generated from the same manifest that
 * the server mounts, adding a defineRoute() endpoint yields its CLI command and
 * doc entry with no separate edit. --check fails the build if the committed
 * outputs are stale.
 */
import * as fs from 'fs';
import * as path from 'path';
import { cliRoutes } from '../src/api/manifest-sources';
import { RouteDef } from '../src/api/route-registry';
import { GeneratedCommand, GeneratedFlag } from '../src/cli/types';

const ROOT = path.join(__dirname, '..');
export const COMMANDS_FILE = path.join(ROOT, 'src', 'cli', 'commands.generated.ts');
export const CLI_DOC_FILE = path.join(ROOT, 'CLI.md');

function toCommand(r: RouteDef): GeneratedCommand {
  const cli = r.cli!;
  const flags: GeneratedFlag[] = (cli.flags ?? []).map((f) => ({
    name: f.name,
    in: f.in,
    ...(f.boolean ? { boolean: true } : {}),
    ...(f.required ? { required: true } : {}),
    ...(f.description ? { description: f.description } : {}),
  }));
  return {
    noun: cli.noun,
    verb: cli.verb,
    method: r.method,
    path: r.path,
    args: cli.args ?? [],
    flags,
    summary: r.summary,
    auth: r.auth,
  };
}

/** Deterministic ordering so regeneration is stable. */
function sortCommands(cmds: GeneratedCommand[]): GeneratedCommand[] {
  return [...cmds].sort((a, b) => (a.noun === b.noun ? a.verb.localeCompare(b.verb) : a.noun.localeCompare(b.noun)));
}

function renderCommandsFile(cmds: GeneratedCommand[]): string {
  const nouns = [...new Set(cmds.map((c) => c.noun))].sort();
  return `// AUTO-GENERATED by scripts/gen-cli.ts — DO NOT EDIT.
// Regenerate with: npm run gen-cli
import { GeneratedCommand } from './types';

export const GENERATED_COMMANDS: GeneratedCommand[] = ${JSON.stringify(cmds, null, 2)};

export const GENERATED_NOUNS: string[] = ${JSON.stringify(nouns)};
`;
}

function usageFor(c: GeneratedCommand): string {
  const positionals = c.args.map((a) => `<${a}>`).join(' ');
  const flagStr = c.flags
    .map((f) => (f.boolean ? `[--${f.name}]` : f.required ? `--${f.name} <v>` : `[--${f.name} <v>]`))
    .join(' ');
  return `claude-gateway ${c.noun} ${c.verb}${positionals ? ' ' + positionals : ''}${flagStr ? ' ' + flagStr : ''}`.trim();
}

function renderDoc(cmds: GeneratedCommand[]): string {
  const nouns = [...new Set(cmds.map((c) => c.noun))].sort();
  let out = `# Claude Gateway — CLI Reference

> **Auto-generated from the route manifest** (\`scripts/gen-cli.ts\`). Do not edit by hand.
> Every command is a thin client over the HTTP API; see \`API.md\` for the raw HTTP reference.

The \`claude-gateway\` binary accepts friendly \`<noun> <verb>\` subcommands. Running it with **no subcommand still boots the server** (unchanged), so systemd/pm2/npm start are unaffected.

## Global flags

| Flag | Meaning |
|------|---------|
| \`--url <url>\` | Gateway base URL (else \`$CLAUDE_GATEWAY_URL\`, else \`config.gateway.publicUrl\`, else \`http://<bind>:<port>\`) |
| \`--key <key>\` | API key (else \`$CLAUDE_GATEWAY_API_KEY\`, else the first admin key in config) |
| \`--json\` | Print the raw JSON response only (stdout reserved for JSON) |
| \`--data <json>\` | JSON object merged into the request body (write commands) |
| \`--help\` | Show help for the command |

## Lifecycle & diagnostics (do not require a running server)

| Command | Description |
|---------|-------------|
| \`claude-gateway gateway status\` | Show whether the gateway is running + version/uptime |
| \`claude-gateway gateway restart\` | Restart via the owning manager (systemd/pm2/foreground) |
| \`claude-gateway gateway stop\` | Stop the gateway |
| \`claude-gateway doctor\` | Check config/env/connectivity |
| \`claude-gateway debug-bundle\` | Write a small redacted diagnostics bundle for a stuck session |
| \`claude-gateway api <METHOD> <path>\` | Escape hatch: call any endpoint directly |

## Resource commands

`;
  for (const noun of nouns) {
    out += `### \`${noun}\`\n\n`;
    out += `| Command | Method | Path | Auth | Description |\n|---------|--------|------|------|-------------|\n`;
    for (const c of cmds.filter((x) => x.noun === noun)) {
      out += `| \`${usageFor(c)}\` | ${c.method} | \`${c.path}\` | ${c.auth} | ${c.summary} |\n`;
    }
    out += '\n';
  }
  return out;
}

/** Build both generated outputs in-memory from the current manifest. Exported so
 *  the drift-guard test can compare them against the committed files. */
export function buildOutputs(): { commands: string; doc: string } {
  const cmds = sortCommands(cliRoutes().map(toCommand));
  return { commands: renderCommandsFile(cmds), doc: renderDoc(cmds) };
}

function main(): void {
  const check = process.argv.includes('--check');
  const { commands: commandsContent, doc: docContent } = buildOutputs();

  if (check) {
    const problems: string[] = [];
    for (const [file, expected] of [
      [COMMANDS_FILE, commandsContent],
      [CLI_DOC_FILE, docContent],
    ] as const) {
      const actual = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : '';
      if (actual !== expected) problems.push(path.relative(ROOT, file));
    }
    if (problems.length) {
      console.error(`gen-cli --check: these generated files are stale, run \`npm run gen-cli\`:\n  ${problems.join('\n  ')}`);
      process.exit(1);
    }
    console.log('gen-cli --check: generated files are up to date.');
    return;
  }

  fs.writeFileSync(COMMANDS_FILE, commandsContent);
  fs.writeFileSync(CLI_DOC_FILE, docContent);
  const count = (commandsContent.match(/"noun":/g) || []).length;
  console.log(`gen-cli: wrote ${count} commands → ${path.relative(ROOT, COMMANDS_FILE)} and ${path.relative(ROOT, CLI_DOC_FILE)}`);
}

if (require.main === module) {
  main();
}
